#!/bin/bash

set -e

NVIDIA_CONTAINER_RUNTIME_HOOK=/usr/bin/nvidia-container-runtime-hook

case "$1" in
    configure)
        /usr/bin/hcu-ctk --quiet config --config-file=/etc/hcu-container-runtime/config.toml --in-place
        if [ ! -e "${NVIDIA_CONTAINER_RUNTIME_HOOK}" ]; then
            ln -s /usr/bin/hcu-ctk $NVIDIA_CONTAINER_RUNTIME_HOOK
        fi

        /usr/bin/hcu-ctk runtime configure --runtime=docker --set-as-default
        if systemctl status docker >/dev/null 2>&1; then
          echo -e "\e[032m ================================== \e[0m"
          echo -e "\e[033m Please restart Docker service:     \e[0m"
          echo -e "\e[033m    sudo systemctl restart docker   \e[0m"
          echo -e "\e[032m ================================== \e[0m"
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
